(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	spectrograph1 - mode
	infrared2 - mode
	infrared0 - mode
	Star12 - direction
	Star8 - direction
	GroundStation5 - direction
	GroundStation11 - direction
	Star9 - direction
	GroundStation6 - direction
	GroundStation1 - direction
	GroundStation3 - direction
	GroundStation4 - direction
	Star0 - direction
	GroundStation7 - direction
	Star2 - direction
	GroundStation14 - direction
	GroundStation13 - direction
	Star10 - direction
	Planet15 - direction
	Star16 - direction
	Planet17 - direction
	Planet18 - direction
	Star19 - direction
	Star20 - direction
	Phenomenon21 - direction
	Star22 - direction
	Planet23 - direction
	Planet24 - direction
	Planet25 - direction
	Phenomenon26 - direction
	Planet27 - direction
	Star28 - direction
	Planet29 - direction
)
(:init
	(supports instrument0 infrared0)
	(supports instrument0 infrared2)
	(supports instrument0 spectrograph1)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 Star12)
	(calibration_target instrument0 GroundStation11)
	(calibration_target instrument0 GroundStation1)
	(supports instrument1 infrared2)
	(supports instrument1 spectrograph1)
	(calibration_target instrument1 Star8)
	(supports instrument2 infrared2)
	(supports instrument2 spectrograph1)
	(calibration_target instrument2 GroundStation14)
	(calibration_target instrument2 GroundStation7)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation3)
	(supports instrument3 spectrograph1)
	(calibration_target instrument3 Star0)
	(calibration_target instrument3 GroundStation5)
	(calibration_target instrument3 GroundStation14)
	(calibration_target instrument3 GroundStation4)
	(calibration_target instrument3 GroundStation1)
	(supports instrument4 infrared2)
	(supports instrument4 spectrograph1)
	(supports instrument4 infrared0)
	(calibration_target instrument4 GroundStation13)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 GroundStation3)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation6)
	(supports instrument5 spectrograph1)
	(supports instrument5 infrared2)
	(supports instrument5 infrared0)
	(calibration_target instrument5 Star0)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 GroundStation11)
	(calibration_target instrument5 GroundStation4)
	(supports instrument6 infrared0)
	(calibration_target instrument6 GroundStation1)
	(calibration_target instrument6 GroundStation4)
	(calibration_target instrument6 Star2)
	(calibration_target instrument6 GroundStation6)
	(supports instrument7 infrared0)
	(supports instrument7 spectrograph1)
	(supports instrument7 infrared2)
	(calibration_target instrument7 GroundStation4)
	(calibration_target instrument7 GroundStation3)
	(calibration_target instrument7 GroundStation13)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 GroundStation14)
	(supports instrument8 infrared0)
	(calibration_target instrument8 GroundStation7)
	(calibration_target instrument8 Star0)
	(calibration_target instrument8 GroundStation4)
	(supports instrument9 infrared0)
	(supports instrument9 infrared2)
	(supports instrument9 spectrograph1)
	(calibration_target instrument9 Star10)
	(calibration_target instrument9 GroundStation13)
	(calibration_target instrument9 GroundStation14)
	(calibration_target instrument9 Star2)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation4)
)
(:goal (and
	(pointing satellite1 Star2)
	(have_image Planet15 infrared2)
	(have_image Star16 infrared2)
	(have_image Planet17 infrared0)
	(have_image Planet18 infrared0)
	(have_image Star19 infrared2)
	(have_image Star20 spectrograph1)
	(have_image Phenomenon21 infrared0)
	(have_image Star22 infrared0)
	(have_image Planet23 infrared2)
	(have_image Planet24 infrared0)
	(have_image Planet25 infrared0)
	(have_image Phenomenon26 infrared0)
	(have_image Planet27 spectrograph1)
	(have_image Star28 infrared0)
	(have_image Planet29 spectrograph1)
))

)
