(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	satellite1 - satellite
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	satellite3 - satellite
	instrument7 - instrument
	instrument8 - instrument
	instrument9 - instrument
	thermograph0 - mode
	infrared2 - mode
	image1 - mode
	GroundStation2 - direction
	Star4 - direction
	GroundStation13 - direction
	Star8 - direction
	GroundStation17 - direction
	GroundStation3 - direction
	GroundStation7 - direction
	GroundStation16 - direction
	Star10 - direction
	Star15 - direction
	Star12 - direction
	Star11 - direction
	Star5 - direction
	GroundStation14 - direction
	GroundStation19 - direction
	GroundStation9 - direction
	Star18 - direction
	GroundStation6 - direction
	Star0 - direction
	Star1 - direction
	Star20 - direction
	Star21 - direction
	Star22 - direction
	Phenomenon23 - direction
	Phenomenon24 - direction
	Planet25 - direction
	Phenomenon26 - direction
	Phenomenon27 - direction
	Star28 - direction
	Planet29 - direction
	Phenomenon30 - direction
	Star31 - direction
	Star32 - direction
	Phenomenon33 - direction
	Phenomenon34 - direction
	Star35 - direction
	Star36 - direction
	Phenomenon37 - direction
	Star38 - direction
	Planet39 - direction
)
(:init
	(supports instrument0 thermograph0)
	(calibration_target instrument0 Star1)
	(calibration_target instrument0 Star10)
	(calibration_target instrument0 Star15)
	(calibration_target instrument0 GroundStation16)
	(calibration_target instrument0 Star11)
	(supports instrument1 infrared2)
	(calibration_target instrument1 GroundStation13)
	(calibration_target instrument1 Star12)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation19)
	(supports instrument2 thermograph0)
	(supports instrument2 image1)
	(calibration_target instrument2 GroundStation9)
	(calibration_target instrument2 GroundStation17)
	(calibration_target instrument2 Star8)
	(calibration_target instrument2 Star18)
	(calibration_target instrument2 Star0)
	(supports instrument3 image1)
	(calibration_target instrument3 GroundStation14)
	(calibration_target instrument3 Star0)
	(supports instrument4 thermograph0)
	(calibration_target instrument4 GroundStation6)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon33)
	(supports instrument5 infrared2)
	(calibration_target instrument5 GroundStation17)
	(supports instrument6 infrared2)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 Star15)
	(calibration_target instrument6 Star0)
	(calibration_target instrument6 GroundStation14)
	(calibration_target instrument6 GroundStation16)
	(calibration_target instrument6 GroundStation7)
	(calibration_target instrument6 GroundStation3)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Phenomenon24)
	(supports instrument7 infrared2)
	(supports instrument7 image1)
	(supports instrument7 thermograph0)
	(calibration_target instrument7 Star12)
	(calibration_target instrument7 Star0)
	(calibration_target instrument7 GroundStation9)
	(calibration_target instrument7 Star15)
	(calibration_target instrument7 GroundStation6)
	(calibration_target instrument7 Star10)
	(supports instrument8 thermograph0)
	(supports instrument8 infrared2)
	(supports instrument8 image1)
	(calibration_target instrument8 GroundStation9)
	(calibration_target instrument8 GroundStation19)
	(calibration_target instrument8 GroundStation14)
	(calibration_target instrument8 Star18)
	(calibration_target instrument8 Star5)
	(calibration_target instrument8 Star11)
	(supports instrument9 image1)
	(calibration_target instrument9 Star1)
	(calibration_target instrument9 Star0)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 Star18)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(power_avail satellite3)
	(pointing satellite3 Phenomenon30)
)
(:goal (and
	(pointing satellite1 Star20)
	(pointing satellite2 GroundStation7)
	(have_image Star20 infrared2)
	(have_image Star21 thermograph0)
	(have_image Star22 image1)
	(have_image Phenomenon23 infrared2)
	(have_image Phenomenon24 image1)
	(have_image Planet25 thermograph0)
	(have_image Phenomenon26 thermograph0)
	(have_image Phenomenon27 thermograph0)
	(have_image Star28 image1)
	(have_image Planet29 image1)
	(have_image Phenomenon30 image1)
	(have_image Star31 thermograph0)
	(have_image Star32 thermograph0)
	(have_image Phenomenon33 image1)
	(have_image Phenomenon34 thermograph0)
	(have_image Star35 infrared2)
	(have_image Star36 image1)
	(have_image Phenomenon37 image1)
	(have_image Star38 thermograph0)
	(have_image Planet39 image1)
))

)
