(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	instrument4 - instrument
	instrument5 - instrument
	satellite2 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	satellite3 - satellite
	instrument9 - instrument
	instrument10 - instrument
	instrument11 - instrument
	instrument12 - instrument
	satellite4 - satellite
	instrument13 - instrument
	spectrograph0 - mode
	spectrograph3 - mode
	infrared1 - mode
	image2 - mode
	GroundStation13 - direction
	GroundStation5 - direction
	Star11 - direction
	GroundStation3 - direction
	GroundStation7 - direction
	Star2 - direction
	GroundStation6 - direction
	Star4 - direction
	Star10 - direction
	GroundStation0 - direction
	GroundStation1 - direction
	GroundStation14 - direction
	GroundStation8 - direction
	GroundStation12 - direction
	GroundStation9 - direction
	Phenomenon15 - direction
	Star16 - direction
	Star17 - direction
	Star18 - direction
	Phenomenon19 - direction
	Star20 - direction
	Planet21 - direction
	Phenomenon22 - direction
	Star23 - direction
	Planet24 - direction
	Phenomenon25 - direction
	Phenomenon26 - direction
	Planet27 - direction
	Phenomenon28 - direction
	Planet29 - direction
)
(:init
	(supports instrument0 image2)
	(calibration_target instrument0 GroundStation9)
	(calibration_target instrument0 GroundStation7)
	(calibration_target instrument0 GroundStation5)
	(calibration_target instrument0 GroundStation8)
	(supports instrument1 spectrograph0)
	(supports instrument1 infrared1)
	(calibration_target instrument1 GroundStation5)
	(calibration_target instrument1 GroundStation6)
	(calibration_target instrument1 GroundStation8)
	(calibration_target instrument1 GroundStation13)
	(calibration_target instrument1 Star4)
	(supports instrument2 spectrograph0)
	(calibration_target instrument2 Star10)
	(calibration_target instrument2 GroundStation14)
	(calibration_target instrument2 GroundStation12)
	(calibration_target instrument2 GroundStation7)
	(calibration_target instrument2 GroundStation9)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Planet24)
	(supports instrument3 spectrograph0)
	(calibration_target instrument3 GroundStation0)
	(calibration_target instrument3 GroundStation9)
	(calibration_target instrument3 Star4)
	(calibration_target instrument3 GroundStation12)
	(calibration_target instrument3 GroundStation6)
	(supports instrument4 image2)
	(supports instrument4 spectrograph0)
	(supports instrument4 spectrograph3)
	(calibration_target instrument4 GroundStation3)
	(calibration_target instrument4 GroundStation7)
	(calibration_target instrument4 Star4)
	(calibration_target instrument4 Star2)
	(supports instrument5 image2)
	(supports instrument5 infrared1)
	(calibration_target instrument5 Star10)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 GroundStation9)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(on_board instrument5 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Planet27)
	(supports instrument6 infrared1)
	(supports instrument6 image2)
	(supports instrument6 spectrograph3)
	(calibration_target instrument6 Star2)
	(calibration_target instrument6 GroundStation0)
	(calibration_target instrument6 GroundStation6)
	(calibration_target instrument6 GroundStation14)
	(calibration_target instrument6 GroundStation3)
	(supports instrument7 image2)
	(calibration_target instrument7 GroundStation3)
	(calibration_target instrument7 GroundStation6)
	(calibration_target instrument7 Star4)
	(calibration_target instrument7 Star11)
	(calibration_target instrument7 GroundStation8)
	(supports instrument8 spectrograph3)
	(supports instrument8 spectrograph0)
	(supports instrument8 infrared1)
	(calibration_target instrument8 GroundStation1)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(on_board instrument8 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star16)
	(supports instrument9 spectrograph0)
	(supports instrument9 image2)
	(supports instrument9 infrared1)
	(calibration_target instrument9 Star4)
	(calibration_target instrument9 GroundStation6)
	(calibration_target instrument9 Star2)
	(calibration_target instrument9 GroundStation0)
	(calibration_target instrument9 GroundStation7)
	(supports instrument10 spectrograph3)
	(calibration_target instrument10 GroundStation1)
	(calibration_target instrument10 GroundStation14)
	(calibration_target instrument10 GroundStation8)
	(calibration_target instrument10 GroundStation0)
	(calibration_target instrument10 Star10)
	(supports instrument11 spectrograph3)
	(calibration_target instrument11 GroundStation14)
	(supports instrument12 spectrograph3)
	(calibration_target instrument12 GroundStation12)
	(calibration_target instrument12 GroundStation8)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(on_board instrument11 satellite3)
	(on_board instrument12 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation8)
	(supports instrument13 spectrograph0)
	(supports instrument13 spectrograph3)
	(calibration_target instrument13 GroundStation9)
	(on_board instrument13 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Star10)
)
(:goal (and
	(pointing satellite0 GroundStation5)
	(pointing satellite1 GroundStation1)
	(pointing satellite3 GroundStation14)
	(pointing satellite4 Phenomenon28)
	(have_image Phenomenon15 image2)
	(have_image Star16 infrared1)
	(have_image Star17 infrared1)
	(have_image Star18 spectrograph0)
	(have_image Phenomenon19 infrared1)
	(have_image Star20 image2)
	(have_image Planet21 spectrograph0)
	(have_image Phenomenon22 spectrograph0)
	(have_image Star23 spectrograph0)
	(have_image Planet24 spectrograph0)
	(have_image Phenomenon25 infrared1)
	(have_image Phenomenon26 spectrograph3)
	(have_image Planet27 infrared1)
	(have_image Phenomenon28 image2)
	(have_image Planet29 image2)
))

)
