(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	instrument1 - instrument
	instrument2 - instrument
	satellite1 - satellite
	instrument3 - instrument
	satellite2 - satellite
	instrument4 - instrument
	instrument5 - instrument
	satellite3 - satellite
	instrument6 - instrument
	instrument7 - instrument
	instrument8 - instrument
	thermograph0 - mode
	thermograph1 - mode
	image2 - mode
	Star1 - direction
	GroundStation14 - direction
	Star7 - direction
	GroundStation11 - direction
	GroundStation3 - direction
	GroundStation12 - direction
	Star9 - direction
	GroundStation2 - direction
	Star10 - direction
	Star6 - direction
	Star0 - direction
	GroundStation4 - direction
	GroundStation5 - direction
	GroundStation8 - direction
	Star13 - direction
	Planet15 - direction
	Phenomenon16 - direction
	Planet17 - direction
	Planet18 - direction
	Phenomenon19 - direction
	Phenomenon20 - direction
	Phenomenon21 - direction
	Phenomenon22 - direction
	Planet23 - direction
	Phenomenon24 - direction
	Phenomenon25 - direction
	Star26 - direction
	Star27 - direction
	Star28 - direction
	Planet29 - direction
)
(:init
	(supports instrument0 image2)
	(supports instrument0 thermograph0)
	(calibration_target instrument0 GroundStation3)
	(calibration_target instrument0 GroundStation14)
	(calibration_target instrument0 Star7)
	(supports instrument1 thermograph0)
	(calibration_target instrument1 Star13)
	(calibration_target instrument1 GroundStation8)
	(supports instrument2 image2)
	(supports instrument2 thermograph1)
	(supports instrument2 thermograph0)
	(calibration_target instrument2 GroundStation11)
	(calibration_target instrument2 GroundStation12)
	(calibration_target instrument2 Star13)
	(calibration_target instrument2 GroundStation8)
	(calibration_target instrument2 GroundStation5)
	(on_board instrument0 satellite0)
	(on_board instrument1 satellite0)
	(on_board instrument2 satellite0)
	(power_avail satellite0)
	(pointing satellite0 GroundStation5)
	(supports instrument3 thermograph1)
	(supports instrument3 image2)
	(calibration_target instrument3 GroundStation11)
	(calibration_target instrument3 Star6)
	(calibration_target instrument3 Star10)
	(calibration_target instrument3 GroundStation3)
	(calibration_target instrument3 Star7)
	(on_board instrument3 satellite1)
	(power_avail satellite1)
	(pointing satellite1 Phenomenon16)
	(supports instrument4 image2)
	(calibration_target instrument4 Star6)
	(calibration_target instrument4 GroundStation5)
	(calibration_target instrument4 GroundStation12)
	(calibration_target instrument4 GroundStation3)
	(supports instrument5 thermograph1)
	(supports instrument5 image2)
	(calibration_target instrument5 GroundStation5)
	(calibration_target instrument5 GroundStation2)
	(calibration_target instrument5 Star9)
	(calibration_target instrument5 GroundStation8)
	(on_board instrument4 satellite2)
	(on_board instrument5 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Star10)
	(supports instrument6 thermograph1)
	(supports instrument6 thermograph0)
	(calibration_target instrument6 Star6)
	(calibration_target instrument6 Star10)
	(supports instrument7 thermograph1)
	(supports instrument7 thermograph0)
	(supports instrument7 image2)
	(calibration_target instrument7 GroundStation4)
	(calibration_target instrument7 GroundStation8)
	(calibration_target instrument7 Star13)
	(calibration_target instrument7 Star0)
	(supports instrument8 thermograph1)
	(supports instrument8 thermograph0)
	(supports instrument8 image2)
	(calibration_target instrument8 Star13)
	(calibration_target instrument8 GroundStation8)
	(calibration_target instrument8 GroundStation5)
	(on_board instrument6 satellite3)
	(on_board instrument7 satellite3)
	(on_board instrument8 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation8)
)
(:goal (and
	(pointing satellite0 Star27)
	(pointing satellite1 Star28)
	(pointing satellite2 Phenomenon21)
	(pointing satellite3 Star0)
	(have_image Planet15 image2)
	(have_image Phenomenon16 thermograph1)
	(have_image Planet17 thermograph0)
	(have_image Planet18 image2)
	(have_image Phenomenon19 thermograph0)
	(have_image Phenomenon20 thermograph0)
	(have_image Phenomenon21 thermograph0)
	(have_image Phenomenon22 thermograph0)
	(have_image Planet23 image2)
	(have_image Phenomenon24 thermograph1)
	(have_image Phenomenon25 image2)
	(have_image Star26 thermograph0)
	(have_image Star27 thermograph0)
	(have_image Star28 image2)
	(have_image Planet29 thermograph1)
))

)
