# !bin/zsh
# This will generate sas file for a dmoain and problem 
# It uses the runs folder and domain file
source .venv/bin/activate

export DOMAIN="downward-main/useful-actions-dataset-main/satellite/runs/optimal/p03-2-2-2-5-7/domain.pddl"

export PROBLEM="downward-main/useful-actions-dataset-main/satellite/runs/optimal/p226-4-4-3-5-1/problem.pddl"

export SAVE_PATH="sas_files/sas_file3.sas"



./downward-main/src/translate/translate.py  $DOMAIN $PROBLEM --sas-file $SAVE_PATH