(define (problem depot-2-2-3-4-4-7) (:domain depots)
(:objects
	depot0 depot1 - Depot
	distributor0 distributor1 - Distributor
	truck0 truck1 truck2 - Truck
	pallet0 pallet1 pallet2 pallet3 - Pallet
	crate0 crate1 crate2 crate3 crate4 crate5 crate6 - Crate
	hoist0 hoist1 hoist2 hoist3 - Hoist)
(:init
	(at pallet0 depot0)
	(clear crate0)
	(at pallet1 depot1)
	(clear pallet1)
	(at pallet2 distributor0)
	(clear crate6)
	(at pallet3 distributor1)
	(clear crate4)
	(at truck0 distributor1)
	(at truck1 distributor1)
	(at truck2 depot0)
	(at hoist0 depot0)
	(available hoist0)
	(at hoist1 depot1)
	(available hoist1)
	(at hoist2 distributor0)
	(available hoist2)
	(at hoist3 distributor1)
	(available hoist3)
	(at crate0 depot0)
	(on crate0 pallet0)
	(at crate1 distributor1)
	(on crate1 pallet3)
	(at crate2 distributor1)
	(on crate2 crate1)
	(at crate3 distributor1)
	(on crate3 crate2)
	(at crate4 distributor1)
	(on crate4 crate3)
	(at crate5 distributor0)
	(on crate5 pallet2)
	(at crate6 distributor0)
	(on crate6 crate5)
)

(:goal (and
		(on crate1 pallet1)
		(on crate2 crate4)
		(on crate3 pallet0)
		(on crate4 pallet3)
	)
))
