(define (problem strips-sat-x-1)
(:domain satellite)
(:objects
	satellite0 - satellite
	instrument0 - instrument
	satellite1 - satellite
	instrument1 - instrument
	instrument2 - instrument
	instrument3 - instrument
	instrument4 - instrument
	satellite2 - satellite
	instrument5 - instrument
	instrument6 - instrument
	instrument7 - instrument
	satellite3 - satellite
	instrument8 - instrument
	instrument9 - instrument
	instrument10 - instrument
	satellite4 - satellite
	instrument11 - instrument
	instrument12 - instrument
	instrument13 - instrument
	thermograph0 - mode
	image2 - mode
	image1 - mode
	infrared3 - mode
	spectrograph4 - mode
	Star2 - direction
	Star14 - direction
	GroundStation0 - direction
	GroundStation13 - direction
	Star11 - direction
	GroundStation10 - direction
	Star12 - direction
	Star9 - direction
	GroundStation6 - direction
	Star4 - direction
	Star1 - direction
	GroundStation3 - direction
	Star5 - direction
	GroundStation7 - direction
	Star8 - direction
	Star15 - direction
	Phenomenon16 - direction
	Planet17 - direction
	Star18 - direction
	Star19 - direction
)
(:init
	(supports instrument0 thermograph0)
	(supports instrument0 infrared3)
	(supports instrument0 image2)
	(calibration_target instrument0 Star8)
	(calibration_target instrument0 Star14)
	(calibration_target instrument0 Star5)
	(on_board instrument0 satellite0)
	(power_avail satellite0)
	(pointing satellite0 Star2)
	(supports instrument1 image2)
	(calibration_target instrument1 GroundStation13)
	(calibration_target instrument1 Star8)
	(calibration_target instrument1 Star11)
	(calibration_target instrument1 Star14)
	(supports instrument2 infrared3)
	(supports instrument2 image2)
	(calibration_target instrument2 GroundStation10)
	(calibration_target instrument2 Star9)
	(supports instrument3 spectrograph4)
	(supports instrument3 image2)
	(calibration_target instrument3 GroundStation0)
	(calibration_target instrument3 GroundStation10)
	(calibration_target instrument3 Star12)
	(calibration_target instrument3 Star11)
	(calibration_target instrument3 Star4)
	(supports instrument4 image2)
	(calibration_target instrument4 Star4)
	(calibration_target instrument4 GroundStation13)
	(calibration_target instrument4 Star1)
	(calibration_target instrument4 Star5)
	(calibration_target instrument4 GroundStation0)
	(on_board instrument1 satellite1)
	(on_board instrument2 satellite1)
	(on_board instrument3 satellite1)
	(on_board instrument4 satellite1)
	(power_avail satellite1)
	(pointing satellite1 GroundStation10)
	(supports instrument5 thermograph0)
	(supports instrument5 spectrograph4)
	(supports instrument5 infrared3)
	(calibration_target instrument5 GroundStation13)
	(supports instrument6 image2)
	(supports instrument6 image1)
	(calibration_target instrument6 GroundStation7)
	(calibration_target instrument6 GroundStation10)
	(calibration_target instrument6 Star12)
	(calibration_target instrument6 GroundStation13)
	(supports instrument7 spectrograph4)
	(supports instrument7 thermograph0)
	(supports instrument7 image2)
	(calibration_target instrument7 Star11)
	(calibration_target instrument7 Star9)
	(calibration_target instrument7 Star1)
	(on_board instrument5 satellite2)
	(on_board instrument6 satellite2)
	(on_board instrument7 satellite2)
	(power_avail satellite2)
	(pointing satellite2 Planet17)
	(supports instrument8 spectrograph4)
	(supports instrument8 image2)
	(supports instrument8 thermograph0)
	(calibration_target instrument8 Star11)
	(calibration_target instrument8 GroundStation13)
	(calibration_target instrument8 GroundStation6)
	(supports instrument9 spectrograph4)
	(calibration_target instrument9 Star12)
	(calibration_target instrument9 Star5)
	(calibration_target instrument9 GroundStation10)
	(calibration_target instrument9 Star11)
	(supports instrument10 image1)
	(calibration_target instrument10 GroundStation6)
	(calibration_target instrument10 Star9)
	(on_board instrument8 satellite3)
	(on_board instrument9 satellite3)
	(on_board instrument10 satellite3)
	(power_avail satellite3)
	(pointing satellite3 GroundStation0)
	(supports instrument11 image1)
	(calibration_target instrument11 GroundStation3)
	(calibration_target instrument11 Star5)
	(calibration_target instrument11 Star1)
	(calibration_target instrument11 Star4)
	(supports instrument12 spectrograph4)
	(supports instrument12 image1)
	(supports instrument12 thermograph0)
	(calibration_target instrument12 GroundStation7)
	(calibration_target instrument12 Star5)
	(supports instrument13 image2)
	(supports instrument13 image1)
	(calibration_target instrument13 Star8)
	(on_board instrument11 satellite4)
	(on_board instrument12 satellite4)
	(on_board instrument13 satellite4)
	(power_avail satellite4)
	(pointing satellite4 Planet17)
)
(:goal (and
	(pointing satellite0 Phenomenon16)
	(pointing satellite1 GroundStation6)
	(pointing satellite2 Star2)
	(pointing satellite4 Star9)
	(have_image Star15 image1)
	(have_image Phenomenon16 image2)
	(have_image Planet17 spectrograph4)
	(have_image Star18 thermograph0)
	(have_image Star19 thermograph0)
))

)
